development:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: podcastapp_development
  pool: 10
  username: root
  password: lbcoffee45_t
  socket: /opt/local/var/run/mysql5/mysqld.sock
  
test:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: podcastapp_test
  pool: 10
  username: root
  password: lbcoffee45_t
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: podcastapp_production
  pool: 10
  username: root
  password: lbcoffee45_t
  socket: /opt/local/var/run/mysql5/mysqld.sock