production:
  solr:
    hostname: localhost
    port: 8983
    log_level: SEVERE

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: SEVERE

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: SEVERE